# Generated by Django 2.0.5 on 2018-06-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
