# Generated by Django 2.0.5 on 2018-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpauth', '0002_auto_20180627_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
